### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by zhs007** [zhs007/jarviscrawlercore#32]
```
(node:5243) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'appendChild' of null
    at addScriptContent (__puppeteer_evaluation_script__:7:21)
    at ExecutionContext.evaluateHandle (/Users/zhs007/zhs007.github/jarviscrawlercore/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/zhs007/zhs007.github/jarviscrawlercore/node_modules/puppeteer/lib/helper.js:108:27)
    at DOMWorld.addScriptTag (/Users/zhs007/zhs007.github/jarviscrawlercore/node_modules/puppeteer/lib/DOMWorld.js:238:29)
  -- ASYNC --
    at Frame.<anonymous> (/Users/zhs007/zhs007.github/jarviscrawlercore/node_modules/puppeteer/lib/helper.js:108:27)
    at attachJQuery (/Users/zhs007/zhs007.github/jarviscrawlercore/src/utils.js:255:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5243) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gumuruhsspj** [comment]
closed? How to solve this?

**Comment by zhs007** [comment]
We added ``async/await``, it's like this

```
/**
 * attachJQuery
 * @param {object} page - page
 */
async function attachJQuery(page) {
  const jquery = await page.evaluate(() => {
    return typeof $;
  });

  if (jquery !== 'function') {
    await page
        .addScriptTag({path: './browser/jquery3.3.1.min.js'})
        .catch((err) => {
          log.error('attachJQuery:addScriptTag', err);
        });

    await page.waitForFunction('typeof $ === "function"').catch((err) => {
      log.error('attachJQuery:waitForFunction', err);
    });
  }
}
```

Finally, we basically removed the dependency on jquery.
